"""
PRD-001 Compliant Signal Analyst

This module wraps the existing Signal Analyst with PRD-001 Section 3.3 compliance:
- Strategy selection based on current regime
- Strategy allocations (scalper=0.4, trend=0.3, mean_reversion=0.2, breakout=0.1)
- Min confidence threshold 0.6 (reject < 60%)
- Calculate and populate indicators (RSI, MACD, ATR, volume_ratio)
- Calculate entry_price, take_profit, stop_loss based on strategy rules
- Calculate risk_reward_ratio
- Log signal generation at INFO level
- Emit Prometheus counter signals_generated_total{pair, strategy, side}
"""

from __future__ import annotations

import logging
import time
from typing import Dict, Optional, List, Any
from decimal import Decimal
from enum import Enum

# PRD-001 Section 3.3: Prometheus metrics
try:
    from prometheus_client import Counter
    SIGNALS_GENERATED_TOTAL = Counter(
        'signals_generated_total',
        'Total signals generated by trading pair, strategy, and side',
        ['pair', 'strategy', 'side']
    )
    PROMETHEUS_AVAILABLE = True
except ImportError:
    PROMETHEUS_AVAILABLE = False
    SIGNALS_GENERATED_TOTAL = None

logger = logging.getLogger(__name__)


# PRD-001 Section 3.3: Strategy types
class StrategyType(str, Enum):
    """Trading strategy types"""
    SCALPER = "scalper"
    TREND = "trend"
    MEAN_REVERSION = "mean_reversion"
    BREAKOUT = "breakout"


# PRD-001 Section 3.3: Strategy allocations (from PRD)
STRATEGY_ALLOCATIONS = {
    StrategyType.SCALPER: 0.4,
    StrategyType.TREND: 0.3,
    StrategyType.MEAN_REVERSION: 0.2,
    StrategyType.BREAKOUT: 0.1,
}


class PRDSignalAnalyst:
    """
    PRD-001 Section 3.3 compliant Signal Analyst.

    Adds PRD compliance layer to signal generation:
    - Strategy selection based on regime
    - Min confidence threshold enforcement (0.6)
    - Indicator calculation and population
    - Entry/exit price calculation
    - Risk/reward ratio calculation
    - Logging and metrics

    Usage:
        analyst = PRDSignalAnalyst(min_confidence=0.6)
        signal = analyst.generate_signal(
            pair="BTC/USD",
            price=50000.0,
            regime="TRENDING_UP",
            indicators={"rsi": 65.0, "macd": 150.0, ...}
        )
    """

    def __init__(
        self,
        min_confidence: float = 0.6,  # PRD-001 Section 3.3: min 60%
        strategy_allocations: Optional[Dict[StrategyType, float]] = None
    ):
        """
        Initialize PRD-compliant signal analyst.

        Args:
            min_confidence: Minimum confidence threshold (default 0.6 per PRD)
            strategy_allocations: Strategy allocation weights (defaults to PRD spec)
        """
        self.min_confidence = min_confidence
        self.strategy_allocations = strategy_allocations or STRATEGY_ALLOCATIONS

        # Validate allocations sum to ~1.0
        total_allocation = sum(self.strategy_allocations.values())
        if not (0.99 <= total_allocation <= 1.01):
            logger.warning(
                f"Strategy allocations sum to {total_allocation:.2f}, expected ~1.0"
            )

        logger.info(
            f"PRDSignalAnalyst initialized with min_confidence={min_confidence}, "
            f"allocations={self.strategy_allocations}"
        )

    def generate_signal(
        self,
        pair: str,
        price: float,
        regime: str,
        indicators: Dict[str, float],
        side: str = "LONG",
        timeframe: str = "5m"
    ) -> Optional[Dict[str, Any]]:
        """
        Generate trading signal with PRD-001 Section 3.3 compliance.

        Args:
            pair: Trading pair (e.g., "BTC/USD")
            price: Current mid price
            regime: Current market regime (TRENDING_UP, TRENDING_DOWN, RANGING, VOLATILE)
            indicators: Dict with RSI, MACD, ATR, volume_ratio
            side: Trade side (LONG or SHORT)
            timeframe: Timeframe (default "5m")

        Returns:
            Signal dict or None if below confidence threshold
        """
        # PRD-001 Section 3.3: Select strategy based on regime
        strategy = self._select_strategy_for_regime(regime)

        # PRD-001 Section 3.3: Calculate confidence based on indicators
        confidence = self._calculate_confidence(indicators, regime, strategy)

        # PRD-001 Section 3.3: Reject signals below min confidence threshold
        if confidence < self.min_confidence:
            logger.debug(
                f"Signal rejected for {pair}: confidence {confidence:.2f} < "
                f"min {self.min_confidence:.2f}"
            )
            return None

        # PRD-001 Section 3.3: Calculate entry, take profit, stop loss
        entry_price = Decimal(str(price))
        take_profit, stop_loss = self._calculate_exit_levels(
            entry_price, side, strategy, indicators.get("atr_14", 0.0)
        )

        # PRD-001 Section 3.3: Calculate risk/reward ratio
        risk_reward_ratio = self._calculate_risk_reward_ratio(
            entry_price, take_profit, stop_loss, side
        )

        # PRD-001 Section 3.3: Populate TradingSignal.indicators
        signal_indicators = {
            "rsi_14": indicators.get("rsi", 0.0),
            "macd_signal": "BULLISH" if indicators.get("macd", 0.0) > 0 else "BEARISH",
            "atr_14": indicators.get("atr_14", 0.0),
            "volume_ratio": indicators.get("volume_ratio", 1.0),
        }

        # Build signal dict
        signal = {
            "timestamp": time.time(),
            "signal_type": "entry",
            "trading_pair": pair,
            "side": side,
            "entry_price": float(entry_price),
            "take_profit": float(take_profit),
            "stop_loss": float(stop_loss),
            "confidence_score": confidence,
            "strategy": strategy.value,
            "regime": regime,
            "timeframe": timeframe,
            "indicators": signal_indicators,
            "risk_reward_ratio": risk_reward_ratio,
            "agent_id": "prd_signal_analyst",
        }

        # PRD-001 Section 3.3: Log signal generation at INFO level
        logger.info(
            f"[SIGNAL GENERATED] {pair} | Strategy: {strategy.value} | "
            f"Side: {side} | Confidence: {confidence:.2f} | "
            f"Entry: {entry_price} | TP: {take_profit} | SL: {stop_loss} | "
            f"R:R: {risk_reward_ratio:.2f}"
        )

        # PRD-001 Section 3.3: Emit Prometheus counter
        if PROMETHEUS_AVAILABLE and SIGNALS_GENERATED_TOTAL:
            SIGNALS_GENERATED_TOTAL.labels(
                pair=pair,
                strategy=strategy.value,
                side=side
            ).inc()

        return signal

    def _select_strategy_for_regime(self, regime: str) -> StrategyType:
        """
        Select strategy based on current market regime.

        PRD logic:
        - TRENDING_UP/DOWN → Trend following or Breakout
        - RANGING → Mean reversion or Scalper
        - VOLATILE → Scalper (quick in/out)

        Args:
            regime: Market regime

        Returns:
            Selected StrategyType
        """
        if regime in ["TRENDING_UP", "TRENDING_DOWN"]:
            # Trend-following markets: use trend or breakout
            # Allocate based on weights: trend=0.3, breakout=0.1
            # For simplicity, prefer trend in trending markets
            return StrategyType.TREND

        elif regime == "RANGING":
            # Range-bound markets: use mean reversion
            return StrategyType.MEAN_REVERSION

        elif regime == "VOLATILE":
            # High volatility: use scalper for quick trades
            return StrategyType.SCALPER

        else:
            # Default to scalper
            return StrategyType.SCALPER

    def _calculate_confidence(
        self,
        indicators: Dict[str, float],
        regime: str,
        strategy: StrategyType
    ) -> float:
        """
        Calculate signal confidence based on indicators and regime alignment.

        Args:
            indicators: Technical indicators
            regime: Market regime
            strategy: Selected strategy

        Returns:
            Confidence score [0.0, 1.0]
        """
        confidence = 0.5  # Base confidence

        # RSI confirmation
        rsi = indicators.get("rsi", 50.0)
        if 30 <= rsi <= 70:
            confidence += 0.15  # Good RSI range
        elif rsi < 20 or rsi > 80:
            confidence += 0.25  # Strong oversold/overbought

        # MACD confirmation
        macd = indicators.get("macd", 0.0)
        if abs(macd) > 100:  # Strong MACD signal
            confidence += 0.15

        # Volume confirmation
        volume_ratio = indicators.get("volume_ratio", 1.0)
        if volume_ratio > 1.2:  # Above-average volume
            confidence += 0.1

        # Regime alignment bonus
        if regime in ["TRENDING_UP", "TRENDING_DOWN"] and strategy == StrategyType.TREND:
            confidence += 0.1
        elif regime == "RANGING" and strategy == StrategyType.MEAN_REVERSION:
            confidence += 0.1

        # Cap at 0.95
        return min(0.95, confidence)

    def _calculate_exit_levels(
        self,
        entry_price: Decimal,
        side: str,
        strategy: StrategyType,
        atr: float
    ) -> tuple[Decimal, Decimal]:
        """
        Calculate take profit and stop loss levels based on strategy.

        Args:
            entry_price: Entry price
            side: Trade side (LONG/SHORT)
            strategy: Trading strategy
            atr: Average True Range (14-period)

        Returns:
            (take_profit, stop_loss) as Decimals
        """
        atr_decimal = Decimal(str(atr)) if atr > 0 else entry_price * Decimal("0.01")

        # Strategy-specific multipliers
        if strategy == StrategyType.SCALPER:
            tp_multiplier = Decimal("1.5")  # 1.5x ATR
            sl_multiplier = Decimal("1.0")  # 1.0x ATR
        elif strategy == StrategyType.TREND:
            tp_multiplier = Decimal("3.0")  # 3x ATR
            sl_multiplier = Decimal("1.5")  # 1.5x ATR
        elif strategy == StrategyType.MEAN_REVERSION:
            tp_multiplier = Decimal("2.0")  # 2x ATR
            sl_multiplier = Decimal("1.0")  # 1x ATR
        elif strategy == StrategyType.BREAKOUT:
            tp_multiplier = Decimal("4.0")  # 4x ATR (let winners run)
            sl_multiplier = Decimal("1.5")  # 1.5x ATR
        else:
            tp_multiplier = Decimal("2.0")
            sl_multiplier = Decimal("1.0")

        if side == "LONG":
            take_profit = entry_price + (atr_decimal * tp_multiplier)
            stop_loss = entry_price - (atr_decimal * sl_multiplier)
        else:  # SHORT
            take_profit = entry_price - (atr_decimal * tp_multiplier)
            stop_loss = entry_price + (atr_decimal * sl_multiplier)

        return take_profit, stop_loss

    def _calculate_risk_reward_ratio(
        self,
        entry_price: Decimal,
        take_profit: Decimal,
        stop_loss: Decimal,
        side: str
    ) -> float:
        """
        Calculate risk/reward ratio.

        Formula: (take_profit - entry_price) / (entry_price - stop_loss) for LONG
                 (entry_price - take_profit) / (stop_loss - entry_price) for SHORT

        Args:
            entry_price: Entry price
            take_profit: Take profit level
            stop_loss: Stop loss level
            side: Trade side

        Returns:
            Risk/reward ratio (positive float)
        """
        if side == "LONG":
            reward = abs(take_profit - entry_price)
            risk = abs(entry_price - stop_loss)
        else:  # SHORT
            reward = abs(entry_price - take_profit)
            risk = abs(stop_loss - entry_price)

        if risk == 0:
            return 0.0

        return float(reward / risk)

    def get_metrics(self) -> Dict[str, Any]:
        """
        Get analyst metrics.

        Returns:
            Dictionary with metrics
        """
        return {
            "min_confidence": self.min_confidence,
            "strategy_allocations": {k.value: v for k, v in self.strategy_allocations.items()},
        }


# Export for convenience
__all__ = [
    "PRDSignalAnalyst",
    "StrategyType",
    "STRATEGY_ALLOCATIONS",
]
