"""
Canonical TradeIntent model.

A TradeIntent represents WHAT the system intends to do (generated by strategy),
BEFORE risk evaluation. It includes full explainability: reasons, inputs, and context.

This is the output of: generate_trade_intent(strategy, market_snapshot)
"""

from datetime import datetime, timezone
from decimal import Decimal
from enum import Enum
from typing import Any
from uuid import uuid4

from pydantic import BaseModel, Field, ConfigDict, field_validator


class TradeSide(str, Enum):
    """Trade direction."""

    LONG = "long"
    SHORT = "short"


class IntentReason(BaseModel):
    """
    Structured reason for why a trade intent was generated.

    Supports full explainability by capturing:
    - The rule/indicator that triggered
    - The actual input values
    - The threshold/condition that was met
    """

    model_config = ConfigDict(frozen=True)

    rule: str = Field(
        ...,
        description="The rule or indicator that triggered (e.g., 'rsi_oversold', 'ema_crossover')",
    )
    description: str = Field(
        ...,
        description="Human-readable description of why this triggered",
    )
    inputs: dict[str, Any] = Field(
        default_factory=dict,
        description="Input values that led to this trigger (e.g., {'rsi': 28, 'threshold': 30})",
    )
    weight: float = Field(
        default=1.0,
        ge=0,
        le=1,
        description="Weight/importance of this reason in the decision (0-1)",
    )


class TradeIntent(BaseModel):
    """
    Canonical TradeIntent model - represents intended trade BEFORE risk evaluation.

    This is a 'System Law' object. Every trade must start as a TradeIntent,
    then pass through risk evaluation to become an ExecutionDecision.

    Key explainability fields:
    - reasons: WHY we want to trade (multiple can combine)
    - indicator_inputs: WHAT indicators showed at decision time
    - risk_context: additional context for risk evaluation

    Immutability enforced via frozen=True.
    """

    model_config = ConfigDict(frozen=True)

    # Schema version for forward compatibility
    schema_version: str = Field(
        default="1.0.0",
        description="Schema version for this contract",
    )

    # Identity
    intent_id: str = Field(
        default_factory=lambda: f"intent_{uuid4().hex[:12]}",
        description="Unique intent identifier",
    )
    strategy_id: str = Field(
        ...,
        description="ID of the strategy that generated this intent",
    )

    # Trade specification
    pair: str = Field(
        ...,
        description="Trading pair (e.g., 'BTC/USD')",
    )
    side: TradeSide = Field(
        ...,
        description="Trade direction",
    )
    entry_price: Decimal = Field(
        ...,
        gt=0,
        description="Target entry price",
    )
    stop_loss: Decimal = Field(
        ...,
        gt=0,
        description="Stop loss price",
    )
    take_profit: Decimal = Field(
        ...,
        gt=0,
        description="Take profit price",
    )
    position_size_usd: Decimal = Field(
        ...,
        gt=0,
        description="Position size in USD",
    )

    # Confidence & Quality
    confidence: float = Field(
        ...,
        ge=0,
        le=1,
        description="Strategy confidence in this signal (0-1)",
    )

    # EXPLAINABILITY - Core requirement
    reasons: list[IntentReason] = Field(
        ...,
        min_length=1,
        description="WHY this intent was generated (must have at least one reason)",
    )
    indicator_inputs: dict[str, Any] = Field(
        default_factory=dict,
        description="Indicator values at decision time (e.g., {'rsi_14': 28.5, 'macd_signal': 'bullish'})",
    )
    market_context: dict[str, Any] = Field(
        default_factory=dict,
        description="Market context at decision time (e.g., {'regime': 'trending', 'volatility': 'high'})",
    )
    risk_context: dict[str, Any] = Field(
        default_factory=dict,
        description="Risk-relevant context for evaluation (e.g., {'daily_pnl': -10.5, 'open_positions': 1})",
    )

    # Timing
    timeframe: str = Field(
        default="5m",
        description="Timeframe this intent was generated for",
    )
    generated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="When this intent was generated",
    )
    valid_until: datetime | None = Field(
        default=None,
        description="Intent expiration time (None = no expiry)",
    )

    # Metadata
    mode: str = Field(
        default="paper",
        description="Trading mode: 'paper' or 'live'",
    )

    @field_validator("entry_price", "stop_loss", "take_profit", "position_size_usd", mode="before")
    @classmethod
    def coerce_to_decimal(cls, v: Any) -> Decimal:
        """Coerce numeric values to Decimal."""
        if isinstance(v, Decimal):
            return v
        return Decimal(str(v))

    @property
    def risk_reward_ratio(self) -> float:
        """Calculate risk/reward ratio."""
        if self.side == TradeSide.LONG:
            risk = float(self.entry_price - self.stop_loss)
            reward = float(self.take_profit - self.entry_price)
        else:
            risk = float(self.stop_loss - self.entry_price)
            reward = float(self.entry_price - self.take_profit)

        if risk <= 0:
            return 0.0
        return reward / risk

    @property
    def primary_reason(self) -> str:
        """Get the primary (highest weight) reason description."""
        if not self.reasons:
            return "unknown"
        sorted_reasons = sorted(self.reasons, key=lambda r: r.weight, reverse=True)
        return sorted_reasons[0].description

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary for serialization."""
        return self.model_dump(mode="json")

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "TradeIntent":
        """Create from dictionary."""
        return cls.model_validate(data)
